import { test, expect } from '@playwright/test';

test('Pre Costing Creation Test', async ({ page }) => {
  await page.goto('https://stagev15.inctl.net/#login');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('Administrator');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.goto('https://stagev15.inctl.net/app/home');
  await page.getByRole('combobox', { name: 'Search or type a command (' }).click();
  await page.getByRole('link', { name: 'Pre Costing List' }).click();
  await page.getByRole('button', { name: 'Add Pre Costing' }).click();
  await page.getByRole('combobox').nth(1).click();
  await page.getByTitle('RMG', { exact: true }).click();
  await page.getByRole('combobox').nth(2).click();
  await page.getByTitle('HUPM0060').click();

  
  await page.locator('form').filter({ hasText: 'fabric_items Fabric Items No' }).getByRole('button').click();
  await page.locator('.rows > .grid-row > .data-row > .row-index').click();
  await page.locator('.form-page > div > .section-body > div > form > div:nth-child(2) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').first().click();
  await page.locator('#awesomplete_list_27').getByText('Advanced Search').click();
  await page.getByRole('link', { name: '% BCI Cotton S/J' }).click();
  await page.locator('.rows > .grid-row > .data-row > .row-index').click();
  await page.locator('div:nth-child(14) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').click();
  await page.getByRole('option', { name: 'Local' }).click();
  await page.locator('.form-page > div > .section-body > div:nth-child(2) > form > div > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').first().click();
  await page.getByRole('option', { name: 'Black', exact: true }).click();
  await page.locator('.form-page > div > .section-body > div:nth-child(2) > form > div:nth-child(2) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').click();
  await page.getByText('GSM-161-0474160.0').click();
  await page.locator('.form-page > div > .section-body > div:nth-child(2) > form > div:nth-child(3) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').click();
  await page.getByText('DIA-00001').click();
  await page.locator('div:nth-child(14) > .frappe-control > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').click();
  await page.getByText('Back', { exact: true }).click();
  await page.getByText('Front', { exact: true }).click();
  await page.locator('.form-column.col-sm-3 > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').first().click();
  await page.locator('.form-column.col-sm-3 > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').first().fill('0.25');
  await page.locator('div:nth-child(6) > .section-body > div:nth-child(2) > form > .frappe-control > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').click();
  await page.locator('div:nth-child(6) > .section-body > div:nth-child(2) > form > .frappe-control > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').fill('5');
  await page.getByRole('button', { name: 'Insert Below' }).first().click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div > form > div:nth-child(2) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').first().click();
  await page.getByRole('paragraph').filter({ hasText: 'Advanced Search' }).click();
  await page.locator('.modal.fade.show > .modal-dialog > .modal-content > .modal-body > div > .form-layout > .form-page > .row.form-section > .section-body > .form-column > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').fill('f');
  await page.locator('.modal.fade.show > .modal-dialog > .modal-content > .modal-body > div > .form-layout > .form-page > .row.form-section > .section-body > .form-column > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').click();
  await page.locator('.modal.fade.show > .modal-dialog > .modal-content > .modal-body > div > .form-layout > .form-page > .row.form-section > .section-body > .form-column > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').fill('fabric');
  await page.locator('.modal.fade.show > .modal-dialog > .modal-content > .modal-body > div > .form-layout > .form-page > .row.form-section > .section-body > .form-column > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').press('Enter');
  await page.getByRole('link', { name: 'Fabrics-0051' }).click();
  await page.getByText('2', { exact: true }).first().click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div > form > div:nth-child(14) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').click();
  await page.getByRole('option', { name: 'Local' }).getByRole('strong').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div:nth-child(2) > form > div > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').first().click();
  await page.locator('#awesomplete_list_82').getByTitle('Black', { exact: true }).click();
  await page.locator('#awesomplete_list_82').getByTitle('Black', { exact: true }).click();
  await page.locator('#awesomplete_list_83').getByText('160.0').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div:nth-child(2) > form > div:nth-child(3) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').click();
  await page.getByRole('option', { name: 'DIA-00001' }).getByRole('strong').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div:nth-child(3) > form > div:nth-child(14) > .frappe-control > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').click();
  await page.locator('#awesomplete_list_94').getByText('Sleeve').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(5) > .section-body > div > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').first().click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(5) > .section-body > div > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').first().fill('0.54');
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(5) > .section-body > div:nth-child(2) > form > div > .form-group > .control-input-wrapper > .control-input > .link-field > .link-btn > .btn-clear').click();
  await page.getByTitle('Kg').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(6) > .section-body > div:nth-child(2) > form > .frappe-control > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(6) > .section-body > div:nth-child(2) > form > .frappe-control > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').fill('6');
  await page.getByText('ESC', { exact: true }).nth(1).click();
  await page.locator('form').filter({ hasText: 'wastage_fabric GMT Wastage 0' }).getByRole('textbox').click();
  await page.locator('form').filter({ hasText: 'wastage_fabric GMT Wastage 0' }).getByRole('textbox').fill('4');
  await page.getByRole('button', { name: 'Add Row' }).nth(2).click();
  await page.locator('div:nth-child(12) > .section-body > .form-column > form > .frappe-control > .grid-field > .form-grid-container > .form-grid > .grid-body > .rows > .grid-row > .data-row > .row-index').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div > form > div:nth-child(2) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').first().fill('sew');
  await page.getByText('Sewing Thread 50/2 Accessories-0018').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div > form > div:nth-child(14) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div > form > div:nth-child(2) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').first().fill('Accessories-0018lo');
  await page.getByRole('option', { name: 'Local' }).getByRole('strong').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(5) > .section-body > div > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').first().click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(5) > .section-body > div > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').first().fill('0.21');
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(5) > .section-body > div:nth-child(2) > form > div > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').click();
  await page.getByRole('option', { name: 'Cone' }).getByRole('strong').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(6) > .section-body > div:nth-child(2) > form > .frappe-control > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').fill('0.2');
  await page.getByRole('button', { name: 'Insert Below' }).first().click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-heading > .toolbar > .row-actions > .btn.btn-danger').click();
  await page.getByText('1', { exact: true }).nth(5).click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div > form > div:nth-child(2) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').first().fill('sew');
  await page.getByRole('option', { name: 'Sewing Thread 50/2 Accessories-0070' }).getByRole('strong').click();
  await page.getByRole('button', { name: 'Insert Below' }).first().click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div > form > div:nth-child(2) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').first().click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div > form > div:nth-child(2) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').first().fill('butto');
  await page.getByText('Button Accessories-0061').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div > form > div:nth-child(14) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div > form > div:nth-child(2) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').first().fill('Accessories-0061l');
  await page.getByRole('option', { name: 'Local' }).getByRole('strong').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(5) > .section-body > div > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').first().click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(5) > .section-body > div > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').first().fill('0.36');
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(5) > .section-body > div:nth-child(2) > form > div > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').click();
  await page.getByRole('option', { name: 'Pcs' }).getByRole('strong').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(6) > .section-body > div:nth-child(2) > form > .frappe-control > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(6) > .section-body > div:nth-child(2) > form > .frappe-control > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').fill('1');
  await page.getByRole('button', { name: 'Insert Below' }).first().click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div > form > div:nth-child(2) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').first().click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div > form > div:nth-child(2) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').first().fill('poly');
  await page.getByText('Poly Bag Accessories-0030').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div > form > div:nth-child(14) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div > form > div:nth-child(14) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').fill('lo');
  await page.getByRole('paragraph').filter({ hasText: 'Local' }).click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(5) > .section-body > div > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').first().click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div > form > div:nth-child(14) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').fill('Local0.');
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(5) > .section-body > div > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').first().fill('14');
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(5) > .section-body > div > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').first().click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(5) > .section-body > div > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').first().click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(5) > .section-body > div > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').first().click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(5) > .section-body > div > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').first().click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(5) > .section-body > div > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').first().fill('0.14');
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(6) > .section-body > div:nth-child(2) > form > .frappe-control > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(6) > .section-body > div:nth-child(2) > form > .frappe-control > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').fill('2');
  await page.getByRole('button', { name: 'Insert Below' }).first().click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div > form > div:nth-child(2) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').first().fill('cart');
  await page.getByText('Carton Accessories-0189').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div > form > div:nth-child(14) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div > .section-body > div > form > div:nth-child(14) > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').fill('lo');
  await page.getByRole('paragraph').filter({ hasText: 'Local' }).click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(5) > .section-body > div > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').first().click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(5) > .section-body > div > form > div > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').first().fill('0.45');
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(6) > .section-body > div:nth-child(2) > form > .frappe-control > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').click();
  await page.locator('.grid-row.grid-row-open > .form-in-grid > .grid-form-body > .form-area > .form-layout > .form-page > div:nth-child(6) > .section-body > div:nth-child(2) > form > .frappe-control > .form-group > .control-input-wrapper > .control-input > .input-with-feedback').fill('3');
  await page.getByText('ESC', { exact: true }).nth(5).click();
  await page.getByRole('tab', { name: 'Operations' }).click();
  await page.getByRole('tabpanel', { name: 'Operations' }).getByRole('combobox').click();
  await page.getByTitle('KOHLS-OPB', { exact: true }).click();
  await page.getByRole('tab', { name: 'Pre Costing Data' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('600');
  await page.getByRole('combobox').nth(2).click();
  await page.getByTitle('120 Days').click();
  await page.getByRole('combobox').nth(3).click();
  await page.getByTitle('Sea', { exact: true }).click();
  await page.getByRole('combobox').nth(4).click();
  await page.getByRole('combobox').nth(4).fill('fob');
  await page.getByTitle('FOB').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('.modal-dialog.msgprint-dialog > .modal-content > .modal-header > .modal-actions > .btn.btn-modal-close').click();
  await page.locator('div:nth-child(12) > div:nth-child(2) > div > form > div > .grid-field > .form-grid-container > .form-grid > .grid-body > .rows > div:nth-child(2) > .data-row > .row-index').click();
  await page.locator('.frappe-control.input-max-width.has-error > .form-group > .control-input-wrapper > .control-input > .link-field > .awesomplete > .input-with-feedback').fill('but');
  await page.getByRole('option', { name: 'Button Accessories-0023' }).getByRole('strong').click();
  await page.getByText('ESC', { exact: true }).nth(3).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
});